server:
  port: ${app.gateway.port}
  shutdown: graceful
  undertow:
    no-request-timeout: 1h
  netty:
    connection-timeout: 1h
    idle-timeout: 1h
    read-timeout: 1h
    write-timeout: 1h
spring:
  application:
    name: ${app.gateway.name}
  cloud:
    gateway:
      httpclient:
        wiretap: true
        connect-timeout: 3600000
        response-timeout: 1h
        pool:
          max-idle-time: 1h
          max-life-time: 1h
      httpserver:
        wiretap: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080,http://localhost:9081,http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
    loadbalancer:
      enabled: true
      ribbon:
        enabled: false
    refresh:
      enabled: false      
    discovery:
      enabled: true
      client:
        health-indicator:
          enabled: true
      reactive:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${app.eureka.server}
    healthcheck:
      enabled: true
  instance:
    hostname: ${app.gateway.eureka.instance.host}
    preferIpAddress: false
    statusPageUrlPath: ${management.context-path}/actuator/info
    healthCheckUrlPath: ${management.context-path}/actuator/health
    lease-renewal-interval-in-seconds: 300
    lease-expiration-duration-in-seconds: 900
management:
  context-path: ${app.gateway.context.path}
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,beans,env
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO
