server:
  port: ${app.gateway.port}
  shutdown: graceful
spring:
  application:
    name: ${app.gateway.name}
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080,http://localhost:9081,http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
    discovery:
      reactive:
        enabled: true
    loadbalancer:
      enabled: true
    refresh:
      enabled: false      
eureka:
  client:
    serviceUrl:
      defaultZone: ${app.eureka.server}
  instance:
    hostname: ${app.gateway.eureka.instance.host}
    preferIpAddress: false
    statusPageUrlPath: ${management.context-path}/actuator/info
    healthCheckUrlPath: ${management.context-path}/actuator/health
management:
  context-path: ${app.gateway.context.path}
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,beans,env
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: INFO
