server:
  port: ${app.engine.port}
spring:
  application:
    name: ${app.engine.name}
  cloud:
    loadbalancer:
      enabled: true
      ribbon:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: ${app.kafka.servers}
    producer:
      client-id: engineProducerClientId
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://${app.mysql.server}/jtetris
    username: jmedina
    password: jmedina
    driver-class-name: com.mysql.cj.jdbc.Driver
  webflux:
    base-path: ${app.engine.context.path} # reactive
reactive:
  feign:
    cloud:
      enabled: true
    ribbon:
      enabled: false  
    loadbalancer:
      enabled: true
    client:
      config:
        httpBinClient:
          options:
            readTimeoutMillis: 2000
            connectTimeoutMillis: 1000
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances: 
      HttpBinClient_getBinWithDelayInSeconds_int:
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
  timelimiter:
    configs:
      default:
        timeoutDuration: 20s
eureka:
  client:
    serviceUrl:
      defaultZone: ${app.eureka.server}
  instance:
    hostname: ${app.engine.eureka.instance.host}
    preferIpAddress: false
    statusPageUrlPath: ${management.context-path}/actuator/info
    healthCheckUrlPath: ${management.context-path}/actuator/health
management:
  context-path: ${app.engine.context.path}
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,beans,env
# Engine App
engine:
  topic:
    nextFigure: nextFigureTopic
    figure: figureTopic
    board: boardTopic
  groupId:
    message: figureMessage
  figures:
    base-url: http://localhost:9083/service-figures/figures
    askForNextFigureUri: /askForNextFigure