server:
  port: ${app.figures.port}
spring:
  application:
    name: ${app.figures.name}
  data:
    mongodb:
      uri: mongodb://${app.mongo.sever}/${figures.mongodb.name}
  kafka:
    bootstrap-servers: ${app.kafka.servers}
    producer:
      client-id: figuresProducerClientId
  webflux:
    base-path: ${app.figures.context.path} # reactive
eureka:
  client:
    serviceUrl:
      defaultZone: ${app.eureka.server}
  instance:
    hostname: ${app.figures.eureka.instance.host}
    preferIpAddress: false
    statusPageUrlPath: ${management.context-path}/actuator/info
    healthCheckUrlPath: ${management.context-path}/actuator/health
management:
  context-path: ${app.figures.context.path}
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: health,info,beans,env
# Figures App
figures:
  topic:
    nextFigure: nextFigureTopic
  mongodb:
    name: ${app.mongo.db.name}
    loadInitial: false
    blockFindAll: false